### ISSUE TITLE
Downloader potential bug

### ISSUE THREAD

**Issue by WilliamHYZhang** [s5tf-team/S5TF#17]
See https://colab.research.google.com/drive/1-ROoq7w-vAaK7F1LgIoAorcQBV0TSjsz

**Comment by rickwierenga** [comment]
I believe this commit fixed that: https://github.com/s5tf-team/S5TF/pull/5/commits/efa6614432b8091ee05beba266e6d5b5c2f800f5. Let me know if you have any other questions.

**Comment by rickwierenga** [comment]
[This colab](https://colab.research.google.com/drive/1hHVxAmwNbMDYNrXb7f-XWEN4BJFtFPwp) works with shell. It might be worth adding your platform check to determine the binary location to `shell` and prefix that to launchPath.

**Comment by rickwierenga** [comment]
Fully functional demo: https://colab.research.google.com/drive/1LP9IYR3OpL0QXMlFHyCBJMWejydVayrx. With https://github.com/s5tf-team/S5TF/pull/9/commits/7c35d659b5ccb99d49af0de2d32f81b823946c8c.

**Comment by rickwierenga** [comment]
@WilliamHYZhang please confirm the bug is fixed.
